---

- name: Install packages ubuntu and debian
  package:
    name:
      #- cockpit
      - curl
      - wget
      #- python
      - python3
      - python3-pip
      - git
      - vim
      - apt-utils
      - lvm2
    state: present
  when: (ansible_distribution == "Debian" and ansible_distribution == "Ubuntu")

- name: Install packages centos7 and RHEL7
  package:
    name:
      - cockpit
      #- podman
      - curl
      - wget
      #- python2
      - python3
      - python3-pip
      - git
      - vim
      - yum-utils
      - device-mapper-persistent-data
      - lvm2
      - epel-release
      - sudo
      - bash-completion
      #- centos-release-scl-rh
      #- centos-release-scl
    state: present
  when: ( ansible_os_family == 'RedHat' or ansible_pkg_mgr == "dnf" or ansible_pkg_mgr == "yum" )


- name: sudoers file
  get_url:
    url: https://raw.githubusercontent.com/habbis/sudoers/master/admins
    dest: /etc/sudoers.d/
    mode: '0440'

- name: Download sshd_config from git repo
  get_url:
    #url: https://gitlab.com/habbis/openssh_config/raw/master/sshd_config
    url: https://repo01.no.habbfarm.net/habbfarm/openssh_config/raw/branch/main/sshd_config
    dest: /etc/ssh/
    mode: '0744'

- name: add right sftp server for rhel/centos in sshd_config
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '/usr/lib/openssh/sftp-server'
    line: "Subsystem  sftp /usr/libexec/openssh/sftp-server"
  when: ( ansible_os_family == 'RedHat' or ansible_pkg_mgr == "dnf" or ansible_pkg_mgr == "yum" )

- name: add group admins for nopasswd sudo
  group:
    name: admins
    state: present

- name: add user called user with sudo right
  user:
    name: ansible
    shell: /bin/bash
    groups: admins
    append: yes

- name: set authorized keys from github to users
  authorized_key:
    user: "{{ item }}"
    state: present
    #key: https://github.com/habbis.keys
    key: https://repo01.no.habbfarm.net/habbfarm/habbfarm_authorized_keys/raw/branch/master/authorized_keys.keys
  loop:
    - root
    - ansible
  ignore_errors: yes


- name: reload sshd
  service:
    name: sshd
